config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # read all
  get "pets", to: "pets#index"
  # create
  get "pets/new", to: "pets#new"
  post "pets", to: "pets#create"
  # read one
  get "pets/:id", to: "pets#show", as: "pet"
  # update
  get "pets/:id/edit", to: "pets#edit", as: "edit_pet"
  patch "pets/:id", to: "pets#update"
  # destroy
  delete "pets/:id", to: "pets#destroy"


  # root to: "pets#index"
  # resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %W[gavião cachorro gato lagarto ]
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.button :submit, class: 'btn btn-info btn-sm' %>

<%= link_to "Voltar", pets_path(@pet), class: 'btn btn-success btn-sm' %>
<% end %>

app/views/pets/edit.html.erb
<div class="container mt-5">
  <h1>Atualizar um pet</h1>

  <%= render "form" %>
</div>

app/views/pets/index.html.erb
<div class="container mt-5">
  <h1>Todos os pets</h1>
  <ul>
    <% @pets.each do |pet| %>
      <li><%= link_to pet.name, pet_path(pet)  %></li>
    <% end %>
  </ul>

  <%= link_to "Adicionar Pet",  pets_new_path, class: 'btn btn-info' %>
</div>

app/views/pets/new.html.erb
<div class="container mt-5">
  <h1>Adicione um pet</h1>

  <%= render "form" %>
</div>

app/views/pets/show.html.erb
<div class="container mt-5">

  <h1><%= @pet.name %><small>(<%= @pet.species %>)</small></h1>

  <ul>
    <li>Endereço: <%= @pet.address %></li>
    <li>Encontrado em: <%= @pet.found_on %></li>
  </ul>

  <%= link_to "Editar #{@pet.name}", edit_pet_path(@pet), class: 'btn btn-info btn-sm' %>
  <%= link_to "Deletar", pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" }, class: "btn btn-danger btn-sm" %>
  <%= link_to "Voltar", pets_path(@pet), class: 'btn btn-success btn-sm' %>
</div>